apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: backstage
  name: guestbook
  namespace: argocd
  annotations:
      # 1. Map to Backstage entity (REQUIRED)
    backstage.io/entity-ref: 'component:default/my-application'

    # 2. Subscribe to notification triggers (add the ones you want)
    notifications.argoproj.io/subscribe.on-sync-succeeded-backstage.backstage: ''
    notifications.argoproj.io/subscribe.on-sync-failed-backstage.backstage: ''
    notifications.argoproj.io/subscribe.on-health-degraded-backstage.backstage: ''
    notifications.argoproj.io/subscribe.on-deployed-backstage.backstage: ''
spec:
  destination:
    namespace: demo-apps
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: ./development/configuration/argocd/apps/kustomize-guestbook/
    repoURL: https://github.com/redhat-appstudio/rhtap-backstage-plugins.git
    targetRevision: main
  - path: ./development/configuration/argocd/apps/jsonnet-guestbook-tla/
    repoURL: https://github.com/redhat-appstudio/rhtap-backstage-plugins.git
    targetRevision: main
  - path: ./development/configuration/argocd/apps/jsonnet-guestbook/
    repoURL: https://github.com/redhat-appstudio/rhtap-backstage-plugins.git
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: backstage
  name: basic-app
  namespace: argocd
  annotations:
      # 1. Map to Backstage entity (REQUIRED)
    backstage.io/entity-ref: 'component:default/my-application'

    # 2. Subscribe to notification triggers (add the ones you want)
    notifications.argoproj.io/subscribe.on-sync-succeeded-backstage.backstage: ''
    notifications.argoproj.io/subscribe.on-sync-failed-backstage.backstage: ''
    notifications.argoproj.io/subscribe.on-health-degraded-backstage.backstage: ''
    notifications.argoproj.io/subscribe.on-deployed-backstage.backstage: ''
spec:
  destination:
    namespace: demo-apps
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: ./development/configuration/argocd/apps/basic-app/
    repoURL: https://github.com/redhat-appstudio/rhtap-backstage-plugins.git
    targetRevision: main
